# Office Supplies Store - Student Practice Notebook

Dataset file: `10_office_supplies_store.csv`

Solve each task in the empty code cell below it.

## Task 1

Load the dataset into a pandas DataFrame.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("10_office_supplies_store.csv",header = 0)

## Task 2

Display the first 10 rows of the DataFrame.

In [4]:
df.head(10)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value
0,10ORD100522,2025-10-19,Freelancer,South,Stationery,UPI,10,15063.47,17,125026.80
1,10ORD100738,2024-01-12,Startup,North,Furniture,Bank Transfer,2,9166.28,27,13382.77
2,10ORD100741,2025-06-25,School,South,Pantry,Bank Transfer,10,24589.43,27,179502.84
3,10ORD100661,2024-12-29,Enterprise,West,Printing,Credit Card,1,17994.69,7,16735.06
4,10ORD100412,2025-06-19,Enterprise,East,Electronics,Debit Card,20,307.87,22,4802.77
5,10ORD100679,2025-08-21,Startup,Central,Furniture,UPI,2,16240.90,16,27284.71
6,10ORD100627,2025-04-08,Enterprise,East,Printing,Net Banking,1,8855.07,10,7969.56
7,10ORD100514,2024-01-20,Startup,South,Electronics,Bank Transfer,5,23698.47,25,88869.26
8,10ORD100860,2024-07-09,Freelancer,North,Furniture,Credit Card,2,2966.99,17,4925.20
9,10ORD100137,2025-06-11,Enterprise,North,Pantry,UPI,1,249.84,24,189.88

## Task 3

Display the last 7 rows of the DataFrame.

In [5]:
df.tail(7)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value
993,10ORD100701,2025-07-02,Enterprise,Central,Furniture,Debit Card,1,20756.01,5,19718.21
994,10ORD100072,2025-07-20,School,East,Furniture,Debit Card,2,11096.09,18,18197.59
995,10ORD100107,2024-03-09,Freelancer,West,Furniture,UPI,4,965.76,28,2781.39
996,10ORD100271,2024-02-28,School,West,Furniture,Credit Card,4,20712.50,18,67937.00
997,10ORD100861,2024-07-03,Freelancer,East,Electronics,Credit Card,2,17613.75,27,25716.08
998,10ORD100436,2025-12-27,Freelancer,South,Printing,Credit Card,5,18031.72,5,85650.67
999,10ORD100103,2024-09-21,Startup,East,Electronics,Debit Card,4,22269.54,8,81951.91

## Task 4

Check the shape of the DataFrame.

In [6]:
df.shape

(1000, 10)

## Task 5

List all column names.

In [7]:
df.columns.tolist()

['Order_ID',
 'Order_Date',
 'Customer_Segment',
 'Region',
 'Product_Category',
 'Payment_Method',
 'Quantity',
 'Unit_Price',
 'Discount_Percent',
 'Order_Value']

## Task 6

Check the data types of all columns.

In [8]:
df.dtypes

Order_ID                str
Order_Date              str
Customer_Segment        str
Region                  str
Product_Category        str
Payment_Method          str
Quantity              int64
Unit_Price          float64
Discount_Percent      int64
Order_Value         float64
dtype: object

## Task 7

Display basic information using info().

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1000 non-null   str
 1   Order_Date        1000 non-null   str
 2   Customer_Segment  1000 non-null   str
 3   Region            1000 non-null   str
 4   Product_Category  1000 non-null   str
 5   Payment_Method    1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Unit_Price        1000 non-null   float64
 8   Discount_Percent  1000 non-null   int64
 9   Order_Value       1000 non-null   float64
dtypes: float64(2), int64(2), str(6)
memory usage: 78.3 KB

## Task 8

Generate summary statistics for numerical columns.

In [10]:
df.describe()

         Quantity    Unit_Price  Discount_Percent    Order_Value
count  1000.00000   1000.000000         1000.0000    1000.000000
mean      5.32600  12583.022980           14.1030   56478.788600
std       5.82904   7271.797901            8.3459   77616.146203
min       1.00000     29.210000            0.0000      49.070000
25%       2.00000   6324.635000            7.0000   11879.745000
50%       3.00000  12760.985000           14.0000   25560.280000
75%       5.00000  18970.367500           21.0000   64649.995000
max      20.00000  24991.950000           28.0000  467023.610000

## Task 9

Generate summary statistics for categorical columns.

In [11]:
df.describe(include='object')

C:\Users\Nallabothula.Naidu\AppData\Local\Temp\ipykernel_10692\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method
count,1000,1000,1000,1000,1000,1000
unique,1000,548,4,5,5,5
top,10ORD100522,2024-09-14,Enterprise,North,Furniture,Net Banking
freq,1,5,260,211,208,234

## Task 10

Check whether the DataFrame contains any missing values.

In [12]:
df.isnull().any().any()

np.False_

## Task 11

Count the missing values in each column.

In [13]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_Segment    0
Region              0
Product_Category    0
Payment_Method      0
Quantity            0
Unit_Price          0
Discount_Percent    0
Order_Value         0
dtype: int64

## Task 12

Check whether there are any duplicate rows.

In [14]:
df.duplicated().any()

np.False_

## Task 13

Count the duplicate rows in the DataFrame.

In [15]:
df.duplicated().sum()

np.int64(0)

## Task 14

Drop duplicate rows if any exist.

In [16]:
df.drop_duplicates()

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value
0,10ORD100522,2025-10-19,Freelancer,South,Stationery,UPI,10,15063.47,17,125026.80
1,10ORD100738,2024-01-12,Startup,North,Furniture,Bank Transfer,2,9166.28,27,13382.77
2,10ORD100741,2025-06-25,School,South,Pantry,Bank Transfer,10,24589.43,27,179502.84
3,10ORD100661,2024-12-29,Enterprise,West,Printing,Credit Card,1,17994.69,7,16735.06
4,10ORD100412,2025-06-19,Enterprise,East,Electronics,Debit Card,20,307.87,22,4802.77
...,...,...,...,...,...,...,...,...,...,...
995,10ORD100107,2024-03-09,Freelancer,West,Furniture,UPI,4,965.76,28,2781.39
996,10ORD100271,2024-02-28,School,West,Furniture,Credit Card,4,20712.50,18,67937.00
997,10ORD100861,2024-07-03,Freelancer,East,Electronics,Credit Card,2,17613.75,27,25716.08
998,10ORD100436,2025-12-27,Freelancer,South,Printing,Credit Card,5,18031.72,5,85650.67
999,10ORD100103,2024-09-21,Startup,East,Electronics,Debit Card,4,22269.54,8,81951.91

## Task 15

Convert the Order_Date column to datetime format.

In [17]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1000 non-null   str
 1   Order_Date        1000 non-null   datetime64[us]
 2   Customer_Segment  1000 non-null   str
 3   Region            1000 non-null   str
 4   Product_Category  1000 non-null   str
 5   Payment_Method    1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Unit_Price        1000 non-null   float64
 8   Discount_Percent  1000 non-null   int64
 9   Order_Value       1000 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(2), str(5)
memory usage: 78.3 KB

## Task 16

Extract only the year from Order_Date into a new column named Order_Year.

In [19]:
df["Order_Year"] = df["Order_Date"].dt.year

## Task 17

Extract the month name from Order_Date into a new column named Order_Month.

In [20]:
df["Order_Month"] = df["Order_Date"].dt.month

In [22]:
df[["Order_Month","Order_Year"]]

     Order_Month  Order_Year
0             10        2025
1              1        2024
2              6        2025
3             12        2024
4              6        2025
..           ...         ...
995            3        2024
996            2        2024
997            7        2024
998           12        2025
999            9        2024

[1000 rows x 2 columns]

## Task 18

Extract the weekday name from Order_Date into a new column named Order_Day.

In [23]:
df["Order_Day"] = df["Order_Date"].dt.day

## Task 19

Display a random sample of 12 rows.

In [ ]:
df.sample(12)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
944,10ORD100485,2025-02-15,Enterprise,West,Printing,UPI,10,6989.56,24,53120.66,2025,2,15
723,10ORD100280,2024-07-03,Freelancer,East,Pantry,UPI,1,5674.58,17,4709.90,2024,7,3
592,10ORD100668,2024-12-10,Freelancer,South,Stationery,Bank Transfer,2,19659.31,27,28702.59,2024,12,10
278,10ORD100082,2025-01-14,Freelancer,South,Pantry,Debit Card,2,16170.24,17,26842.60,2025,1,14
948,10ORD100244,2024-01-25,Freelancer,South,Printing,UPI,3,21985.07,2,64636.11,2024,1,25
644,10ORD100375,2025-12-11,School,West,Printing,Net Banking,10,16530.49,11,147121.36,2025,12,11
467,10ORD100418,2024-01-17,School,North,Stationery,Bank Transfer,3,14352.32,18,35306.71,2024,1,17
516,10ORD100223,2024-10-12,Startup,Central,Pantry,UPI,10,18840.85,17,156379.06,2024,10,12
414,10ORD100818,2024-01-28,Startup,South,Printing,Net Banking,10,19702.45,20,157619.60,2024,1,28
902,10ORD100270,2025-08-23,Startup,South,Stationery,Bank Transfer,10,1833.97,23,14121.57,2025,8,23
142,10ORD100722,2024-12-14,Enterprise,North,Stationery,Debit Card,2,5887.12,19,9537.13,2024,12,14
560,10ORD100196,2025-10-10,School,Central,Printing,Bank Transfer,3,17350.18,6,48927.51,2025,10,10

## Task 20

Rename Discount_Percent to Discount.

In [25]:
df.rename(columns = {"Discount_Percent":"Discount"})

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount,Order_Value,Order_Year,Order_Month,Order_Day
0,10ORD100522,2025-10-19,Freelancer,South,Stationery,UPI,10,15063.47,17,125026.80,2025,10,19
1,10ORD100738,2024-01-12,Startup,North,Furniture,Bank Transfer,2,9166.28,27,13382.77,2024,1,12
2,10ORD100741,2025-06-25,School,South,Pantry,Bank Transfer,10,24589.43,27,179502.84,2025,6,25
3,10ORD100661,2024-12-29,Enterprise,West,Printing,Credit Card,1,17994.69,7,16735.06,2024,12,29
4,10ORD100412,2025-06-19,Enterprise,East,Electronics,Debit Card,20,307.87,22,4802.77,2025,6,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,10ORD100107,2024-03-09,Freelancer,West,Furniture,UPI,4,965.76,28,2781.39,2024,3,9
996,10ORD100271,2024-02-28,School,West,Furniture,Credit Card,4,20712.50,18,67937.00,2024,2,28
997,10ORD100861,2024-07-03,Freelancer,East,Electronics,Credit Card,2,17613.75,27,25716.08,2024,7,3
998,10ORD100436,2025-12-27,Freelancer,South,Printing,Credit Card,5,18031.72,5,85650.67,2025,12,27
999,10ORD100103,2024-09-21,Startup,East,Electronics,Debit Card,4,22269.54,8,81951.91,2024,9,21

## Task 21

Change the column name back from Discount to Discount_Percent.

In [26]:
df.rename(columns = {"Discount":"Discount_Percent"})

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
0,10ORD100522,2025-10-19,Freelancer,South,Stationery,UPI,10,15063.47,17,125026.80,2025,10,19
1,10ORD100738,2024-01-12,Startup,North,Furniture,Bank Transfer,2,9166.28,27,13382.77,2024,1,12
2,10ORD100741,2025-06-25,School,South,Pantry,Bank Transfer,10,24589.43,27,179502.84,2025,6,25
3,10ORD100661,2024-12-29,Enterprise,West,Printing,Credit Card,1,17994.69,7,16735.06,2024,12,29
4,10ORD100412,2025-06-19,Enterprise,East,Electronics,Debit Card,20,307.87,22,4802.77,2025,6,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,10ORD100107,2024-03-09,Freelancer,West,Furniture,UPI,4,965.76,28,2781.39,2024,3,9
996,10ORD100271,2024-02-28,School,West,Furniture,Credit Card,4,20712.50,18,67937.00,2024,2,28
997,10ORD100861,2024-07-03,Freelancer,East,Electronics,Credit Card,2,17613.75,27,25716.08,2024,7,3
998,10ORD100436,2025-12-27,Freelancer,South,Printing,Credit Card,5,18031.72,5,85650.67,2025,12,27
999,10ORD100103,2024-09-21,Startup,East,Electronics,Debit Card,4,22269.54,8,81951.91,2024,9,21

## Task 22

Set Order_ID as the index.

In [27]:
df.set_index('Order_ID')

,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
Order_ID,,,,,,,,,,,,
10ORD100522,2025-10-19,Freelancer,South,Stationery,UPI,10,15063.47,17,125026.80,2025,10,19
10ORD100738,2024-01-12,Startup,North,Furniture,Bank Transfer,2,9166.28,27,13382.77,2024,1,12
10ORD100741,2025-06-25,School,South,Pantry,Bank Transfer,10,24589.43,27,179502.84,2025,6,25
10ORD100661,2024-12-29,Enterprise,West,Printing,Credit Card,1,17994.69,7,16735.06,2024,12,29
10ORD100412,2025-06-19,Enterprise,East,Electronics,Debit Card,20,307.87,22,4802.77,2025,6,19
...,...,...,...,...,...,...,...,...,...,...,...,...
10ORD100107,2024-03-09,Freelancer,West,Furniture,UPI,4,965.76,28,2781.39,2024,3,9
10ORD100271,2024-02-28,School,West,Furniture,Credit Card,4,20712.50,18,67937.00,2024,2,28
10ORD100861,2024-07-03,Freelancer,East,Electronics,Credit Card,2,17613.75,27,25716.08,2024,7,3
10ORD100436,2025-12-27,Freelancer,South,Printing,Credit Card,5,18031.72,5,85650.67,2025,12,27
10ORD100103,2024-09-21,Startup,East,Electronics,Debit Card,4,22269.54,8,81951.91,2024,9,21

## Task 23

Reset the index back to default integer index.

In [28]:
df = df.reset_index(drop=True)

## Task 24

Sort the DataFrame by Order_Value in descending order.

In [29]:
df.sort_values('Order_Value', ascending=False)

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
427,10ORD100062,2025-11-17,Enterprise,Central,Electronics,Bank Transfer,20,24580.19,5,467023.61,2025,11,17
921,10ORD100035,2024-11-13,Startup,East,Electronics,Net Banking,20,23755.17,8,437095.13,2024,11,13
665,10ORD100227,2025-10-18,Startup,South,Stationery,Bank Transfer,20,22317.62,9,406180.68,2025,10,18
386,10ORD100501,2025-07-13,Startup,East,Electronics,Net Banking,20,20519.62,3,398080.63,2025,7,13
940,10ORD100841,2024-06-06,Freelancer,East,Stationery,UPI,20,21601.38,8,397465.39,2024,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
645,10ORD100470,2024-02-06,Freelancer,East,Printing,Bank Transfer,3,83.24,13,217.26,2024,2,6
9,10ORD100137,2025-06-11,Enterprise,North,Pantry,UPI,1,249.84,24,189.88,2025,6,11
413,10ORD100265,2025-04-08,Startup,East,Printing,UPI,1,180.68,4,173.45,2025,4,8
613,10ORD100713,2025-04-23,Enterprise,East,Furniture,Net Banking,2,54.65,13,95.09,2025,4,23
618,10ORD100985,2024-01-03,Freelancer,Central,Pantry,Net Banking,2,29.21,16,49.07,2024,1,3

## Task 25

Sort the DataFrame by Quantity ascending and Unit_Price descending.

In [37]:
df.sort_values(by=['Quantity', 'Unit_Price'], ascending=[True, False])

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
700,10ORD100789,2025-07-21,School,East,Stationery,Net Banking,1,24838.88,3,24093.71,2025,7,21
182,10ORD100378,2025-07-14,Freelancer,Central,Electronics,Net Banking,1,24507.86,10,22057.07,2025,7,14
137,10ORD100216,2025-08-22,School,Central,Furniture,Bank Transfer,1,24491.38,7,22776.98,2025,8,22
211,10ORD100142,2024-09-20,School,West,Electronics,Bank Transfer,1,24436.81,6,22970.60,2024,9,20
339,10ORD100533,2024-11-22,School,North,Printing,Bank Transfer,1,24377.75,27,17795.76,2024,11,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,10ORD100425,2024-05-03,Freelancer,West,Stationery,Net Banking,20,797.61,11,14197.46,2024,5,3
556,10ORD100370,2024-03-25,School,East,Stationery,Credit Card,20,707.07,7,13151.50,2024,3,25
632,10ORD100284,2025-11-13,School,South,Furniture,Net Banking,20,541.60,25,8124.00,2025,11,13
766,10ORD100374,2024-07-17,Freelancer,North,Electronics,UPI,20,343.28,21,5423.82,2024,7,17
4,10ORD100412,2025-06-19,Enterprise,East,Electronics,Debit Card,20,307.87,22,4802.77,2025,6,19

## Task 26

Filter all rows where Region is North.

In [40]:
cond = df["Region"] == "North"
df[cond]

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
339,10ORD100533,2024-11-22,School,North,Printing,Bank Transfer,1,24377.75,27,17795.76,2024,11,22
102,10ORD100937,2025-02-17,Startup,North,Electronics,UPI,1,24251.24,11,21583.60,2025,2,17
468,10ORD100526,2025-10-17,School,North,Printing,Debit Card,1,24131.04,3,23407.11,2025,10,17
238,10ORD100193,2024-02-27,Enterprise,North,Pantry,Bank Transfer,1,24083.21,21,19025.74,2024,2,27
384,10ORD100221,2025-10-31,School,North,Printing,Bank Transfer,1,22586.65,6,21231.45,2025,10,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,10ORD100480,2024-09-16,Enterprise,North,Furniture,Credit Card,20,2922.28,28,42080.83,2024,9,16
585,10ORD100408,2024-12-11,Startup,North,Stationery,Debit Card,20,2018.78,22,31492.97,2024,12,11
389,10ORD100775,2025-06-17,Enterprise,North,Printing,Debit Card,20,1969.49,6,37026.41,2025,6,17
584,10ORD100809,2024-01-13,Startup,North,Pantry,UPI,20,1820.00,28,26208.00,2024,1,13
766,10ORD100374,2024-07-17,Freelancer,North,Electronics,UPI,20,343.28,21,5423.82,2024,7,17

## Task 27

Filter all rows where Payment_Method is UPI.

In [41]:
cond = df["Payment_Method"] == "UPI"
df[cond]

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
102,10ORD100937,2025-02-17,Startup,North,Electronics,UPI,1,24251.24,11,21583.60,2025,2,17
786,10ORD100954,2025-10-15,School,Central,Stationery,UPI,1,24135.53,3,23411.46,2025,10,15
900,10ORD100816,2024-10-01,School,West,Furniture,UPI,1,22598.88,11,20113.00,2024,10,1
196,10ORD100333,2024-03-03,Enterprise,Central,Furniture,UPI,1,21645.26,12,19047.83,2024,3,3
638,10ORD100438,2025-07-04,Enterprise,East,Furniture,UPI,1,21380.05,15,18173.04,2025,7,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
956,10ORD100476,2025-04-12,Freelancer,South,Furniture,UPI,20,3957.84,23,60950.74,2025,4,12
510,10ORD100258,2024-01-01,Enterprise,North,Electronics,UPI,20,3282.67,26,48583.52,2024,1,1
584,10ORD100809,2024-01-13,Startup,North,Pantry,UPI,20,1820.00,28,26208.00,2024,1,13
228,10ORD100905,2024-03-23,School,Central,Electronics,UPI,20,1419.02,2,27812.79,2024,3,23
766,10ORD100374,2024-07-17,Freelancer,North,Electronics,UPI,20,343.28,21,5423.82,2024,7,17

## Task 28

Filter all rows where Quantity is greater than 3.

In [42]:
cond = df["Quantity"] > 3 
df[cond]

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
769,10ORD100234,2025-10-03,Enterprise,Central,Pantry,UPI,4,24896.88,18,81661.77,2025,10,3
225,10ORD100003,2025-08-29,Freelancer,West,Pantry,UPI,4,24887.14,25,74661.42,2025,8,29
226,10ORD100545,2024-12-23,School,North,Printing,Credit Card,4,24823.40,2,97307.73,2024,12,23
472,10ORD100931,2025-06-13,Startup,South,Stationery,Credit Card,4,24629.75,28,70933.68,2025,6,13
10,10ORD100812,2024-09-14,Enterprise,South,Stationery,UPI,4,24397.60,24,74168.70,2024,9,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,10ORD100425,2024-05-03,Freelancer,West,Stationery,Net Banking,20,797.61,11,14197.46,2024,5,3
556,10ORD100370,2024-03-25,School,East,Stationery,Credit Card,20,707.07,7,13151.50,2024,3,25
632,10ORD100284,2025-11-13,School,South,Furniture,Net Banking,20,541.60,25,8124.00,2025,11,13
766,10ORD100374,2024-07-17,Freelancer,North,Electronics,UPI,20,343.28,21,5423.82,2024,7,17
4,10ORD100412,2025-06-19,Enterprise,East,Electronics,Debit Card,20,307.87,22,4802.77,2025,6,19

## Task 29

Filter all rows where Order_Value is above 5000.

In [45]:
cond = df["Order_Value"] > 5000 
df[cond]

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
700,10ORD100789,2025-07-21,School,East,Stationery,Net Banking,1,24838.88,3,24093.71,2025,7,21
182,10ORD100378,2025-07-14,Freelancer,Central,Electronics,Net Banking,1,24507.86,10,22057.07,2025,7,14
137,10ORD100216,2025-08-22,School,Central,Furniture,Bank Transfer,1,24491.38,7,22776.98,2025,8,22
211,10ORD100142,2024-09-20,School,West,Electronics,Bank Transfer,1,24436.81,6,22970.60,2024,9,20
339,10ORD100533,2024-11-22,School,North,Printing,Bank Transfer,1,24377.75,27,17795.76,2024,11,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...
799,10ORD100847,2025-12-24,Enterprise,West,Printing,Debit Card,20,1141.91,28,16443.50,2025,12,24
357,10ORD100425,2024-05-03,Freelancer,West,Stationery,Net Banking,20,797.61,11,14197.46,2024,5,3
556,10ORD100370,2024-03-25,School,East,Stationery,Credit Card,20,707.07,7,13151.50,2024,3,25
632,10ORD100284,2025-11-13,School,South,Furniture,Net Banking,20,541.60,25,8124.00,2025,11,13
766,10ORD100374,2024-07-17,Freelancer,North,Electronics,UPI,20,343.28,21,5423.82,2024,7,17

## Task 30

Filter rows where Discount_Percent is between 10 and 20.

In [46]:
df[(df['Discount_Percent'] >= 10) & (df['Discount_Percent'] <= 20)]

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
182,10ORD100378,2025-07-14,Freelancer,Central,Electronics,Net Banking,1,24507.86,10,22057.07,2025,7,14
102,10ORD100937,2025-02-17,Startup,North,Electronics,UPI,1,24251.24,11,21583.60,2025,2,17
362,10ORD100136,2025-12-24,School,East,Printing,Net Banking,1,23352.57,10,21017.31,2025,12,24
173,10ORD100990,2025-02-09,Freelancer,South,Electronics,Credit Card,1,22871.47,20,18297.18,2025,2,9
900,10ORD100816,2024-10-01,School,West,Furniture,UPI,1,22598.88,11,20113.00,2024,10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,10ORD100558,2024-08-04,Startup,South,Printing,Credit Card,20,3683.57,17,61147.26,2024,8,4
758,10ORD100442,2025-05-19,Startup,Central,Pantry,Debit Card,20,3080.89,20,49294.24,2025,5,19
130,10ORD100600,2024-04-16,Startup,West,Electronics,Net Banking,20,1227.06,18,20123.78,2024,4,16
549,10ORD100127,2024-02-24,Freelancer,Central,Printing,Bank Transfer,20,1222.05,13,21263.67,2024,2,24
357,10ORD100425,2024-05-03,Freelancer,West,Stationery,Net Banking,20,797.61,11,14197.46,2024,5,3

## Task 31

Filter rows where Product_Category belongs to a given list of two categories.

In [47]:
df[df['Product_Category'].isin(['Stationery', 'Furniture'])]

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day
700,10ORD100789,2025-07-21,School,East,Stationery,Net Banking,1,24838.88,3,24093.71,2025,7,21
137,10ORD100216,2025-08-22,School,Central,Furniture,Bank Transfer,1,24491.38,7,22776.98,2025,8,22
786,10ORD100954,2025-10-15,School,Central,Stationery,UPI,1,24135.53,3,23411.46,2025,10,15
954,10ORD100783,2025-02-01,Startup,West,Furniture,Bank Transfer,1,24110.82,25,18083.11,2025,2,1
785,10ORD100225,2024-07-25,School,Central,Furniture,Credit Card,1,23660.22,5,22477.21,2024,7,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,10ORD100408,2024-12-11,Startup,North,Stationery,Debit Card,20,2018.78,22,31492.97,2024,12,11
375,10ORD100746,2024-03-15,School,West,Furniture,Debit Card,20,1424.81,22,22227.04,2024,3,15
357,10ORD100425,2024-05-03,Freelancer,West,Stationery,Net Banking,20,797.61,11,14197.46,2024,5,3
556,10ORD100370,2024-03-25,School,East,Stationery,Credit Card,20,707.07,7,13151.50,2024,3,25
632,10ORD100284,2025-11-13,School,South,Furniture,Net Banking,20,541.60,25,8124.00,2025,11,13

## Task 32

Find all unique values in Customer_Segment.

In [48]:
df["Customer_Segment"].unique()

<StringArray>
['School', 'Freelancer', 'Startup', 'Enterprise']
Length: 4, dtype: str

## Task 33

Count the number of unique values in Product_Category.

In [50]:
df["Product_Category"].nunique()

5

## Task 34

Display value counts for Region.

In [51]:
df['Region'].value_counts()

Region
North      211
Central    206
South      204
East       201
West       178
Name: count, dtype: int64

## Task 35

Display value counts for Payment_Method.

In [52]:
df['Payment_Method'].value_counts()

Payment_Method
Net Banking      234
UPI              198
Bank Transfer    196
Credit Card      190
Debit Card       182
Name: count, dtype: int64

## Task 36

Find the minimum, maximum, and mean of Unit_Price.

In [57]:
max = df["Unit_Price"].max()
min = df["Unit_Price"].min()
mean = df["Unit_Price"].mean()
print(max,)
print(min)
print(mean)

24991.95
29.21
12583.02298

## Task 37

Find the total sum of Order_Value.

In [58]:
df["Order_Value"].sum()

np.float64(56478788.599999994)

## Task 38

Find the median of Quantity.

In [59]:
df["Quantity"].median()

np.float64(3.0)

## Task 39

Find the standard deviation of Order_Value.

In [60]:
df['Order_Value'].std()

np.float64(77616.1462027844)

## Task 40

Create a new column Gross_Value as Quantity multiplied by Unit_Price.

In [ ]:
df["Gross_Value"] = df["Quantity"] * df["Unit_Price"]

## Task 41

Verify whether Gross_Value and Order_Value are consistent after discount calculation.

In [69]:
df['Modify_1'] = df['Gross_Value']*(1 - df['Discount_Percent'] /100)

In [70]:

df['consistent'] = df['Order_Value'].round(2) == df['Modify_1'].round(2)

In [71]:
df

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Gross_Value,Modify_1,consistent
700,10ORD100789,2025-07-21,School,East,Stationery,Net Banking,1,24838.88,3,24093.71,2025,7,21,24838.88,24093.7136,True
182,10ORD100378,2025-07-14,Freelancer,Central,Electronics,Net Banking,1,24507.86,10,22057.07,2025,7,14,24507.86,22057.0740,True
137,10ORD100216,2025-08-22,School,Central,Furniture,Bank Transfer,1,24491.38,7,22776.98,2025,8,22,24491.38,22776.9834,True
211,10ORD100142,2024-09-20,School,West,Electronics,Bank Transfer,1,24436.81,6,22970.60,2024,9,20,24436.81,22970.6014,True
339,10ORD100533,2024-11-22,School,North,Printing,Bank Transfer,1,24377.75,27,17795.76,2024,11,22,24377.75,17795.7575,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,10ORD100425,2024-05-03,Freelancer,West,Stationery,Net Banking,20,797.61,11,14197.46,2024,5,3,15952.20,14197.4580,True
556,10ORD100370,2024-03-25,School,East,Stationery,Credit Card,20,707.07,7,13151.50,2024,3,25,14141.40,13151.5020,True
632,10ORD100284,2025-11-13,School,South,Furniture,Net Banking,20,541.60,25,8124.00,2025,11,13,10832.00,8124.0000,True
766,10ORD100374,2024-07-17,Freelancer,North,Electronics,UPI,20,343.28,21,5423.82,2024,7,17,6865.60,5423.8240,True
4,10ORD100412,2025-06-19,Enterprise,East,Electronics,Debit Card,20,307.87,22,4802.77,2025,6,19,6157.40,4802.7720,True

## Task 42

Create a new column Discount_Amount.

In [73]:
df['Discount_Amount'] = df['Gross_Value']*df['Discount_Percent']/100
df["Discount_Amount"]

700     745.1664
182    2450.7860
137    1714.3966
211    1466.2086
339    6581.9925
         ...
357    1754.7420
556     989.8980
632    2708.0000
766    1441.7760
4      1354.6280
Name: Discount_Amount, Length: 1000, dtype: float64

## Task 43

Create a new column High_Value_Order where Order_Value > 5000 is Yes otherwise No.

In [74]:
df['High_Value_Order'] = df['Order_Value'].where(df['Order_Value'] > 5000)

## Task 44

Use apply() to categorize Unit_Price into Low, Medium, High.

In [76]:
def category(p):
    if p < 5000:
        return 'Low'
    elif p <= 15000:
        return 'Medium'
    else:
        return 'High'

df["price_category"] = df['Unit_Price'].apply(category)
df["price_category"]

700    High
182    High
137    High
211    High
339    High
       ...
357     Low
556     Low
632     Low
766     Low
4       Low
Name: price_category, Length: 1000, dtype: str

## Task 45

Find the top 10 highest Order_Value rows.

In [77]:
df.nlargest(10, 'Order_Value')

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Gross_Value,Modify_1,consistent,Discount_Amount,High_Value_Order,price_category
427,10ORD100062,2025-11-17,Enterprise,Central,Electronics,Bank Transfer,20,24580.19,5,467023.61,2025,11,17,491603.8,467023.610,True,24580.190,467023.61,High
921,10ORD100035,2024-11-13,Startup,East,Electronics,Net Banking,20,23755.17,8,437095.13,2024,11,13,475103.4,437095.128,True,38008.272,437095.13,High
665,10ORD100227,2025-10-18,Startup,South,Stationery,Bank Transfer,20,22317.62,9,406180.68,2025,10,18,446352.4,406180.684,True,40171.716,406180.68,High
386,10ORD100501,2025-07-13,Startup,East,Electronics,Net Banking,20,20519.62,3,398080.63,2025,7,13,410392.4,398080.628,True,12311.772,398080.63,High
940,10ORD100841,2024-06-06,Freelancer,East,Stationery,UPI,20,21601.38,8,397465.39,2024,6,6,432027.6,397465.392,True,34562.208,397465.39,High
920,10ORD100206,2025-01-13,Enterprise,North,Pantry,Debit Card,20,24519.25,20,392308.00,2025,1,13,490385.0,392308.000,True,98077.000,392308.00,High
257,10ORD100917,2024-05-30,Enterprise,East,Electronics,Debit Card,20,22117.54,14,380421.69,2024,5,30,442350.8,380421.688,True,61929.112,380421.69,High
929,10ORD100898,2025-07-02,Enterprise,North,Furniture,Credit Card,20,23069.39,18,378338.00,2025,7,2,461387.8,378337.996,True,83049.804,378338.00,High
961,10ORD100561,2025-09-30,Startup,Central,Furniture,UPI,20,24846.40,25,372696.00,2025,9,30,496928.0,372696.000,True,124232.000,372696.00,High
765,10ORD100672,2025-03-27,Freelancer,South,Stationery,UPI,20,23565.99,21,372342.64,2025,3,27,471319.8,372342.642,True,98977.158,372342.64,High

## Task 46

Find the bottom 10 lowest Order_Value rows.

In [78]:
df.nsmallest(10, 'Order_Value')

,Order_ID,Order_Date,Customer_Segment,Region,Product_Category,Payment_Method,Quantity,Unit_Price,Discount_Percent,Order_Value,Order_Year,Order_Month,Order_Day,Gross_Value,Modify_1,consistent,Discount_Amount,High_Value_Order,price_category
618,10ORD100985,2024-01-03,Freelancer,Central,Pantry,Net Banking,2,29.21,16,49.07,2024,1,3,58.42,49.0728,True,9.3472,NaN,Low
613,10ORD100713,2025-04-23,Enterprise,East,Furniture,Net Banking,2,54.65,13,95.09,2025,4,23,109.30,95.0910,True,14.2090,NaN,Low
413,10ORD100265,2025-04-08,Startup,East,Printing,UPI,1,180.68,4,173.45,2025,4,8,180.68,173.4528,True,7.2272,NaN,Low
9,10ORD100137,2025-06-11,Enterprise,North,Pantry,UPI,1,249.84,24,189.88,2025,6,11,249.84,189.8784,True,59.9616,NaN,Low
645,10ORD100470,2024-02-06,Freelancer,East,Printing,Bank Transfer,3,83.24,13,217.26,2024,2,6,249.72,217.2564,True,32.4636,NaN,Low
307,10ORD100577,2025-10-26,Startup,Central,Printing,Net Banking,1,339.62,13,295.47,2025,10,26,339.62,295.4694,True,44.1506,NaN,Low
156,10ORD100310,2024-10-04,Freelancer,North,Furniture,Bank Transfer,4,104.26,2,408.70,2024,10,4,417.04,408.6992,True,8.3408,NaN,Low
478,10ORD100606,2025-11-11,Enterprise,West,Pantry,Net Banking,5,98.09,9,446.31,2025,11,11,490.45,446.3095,True,44.1405,NaN,Low
243,10ORD100800,2024-09-21,Freelancer,South,Furniture,Debit Card,1,521.59,12,459.00,2024,9,21,521.59,458.9992,True,62.5908,NaN,Low
291,10ORD100797,2025-02-10,Freelancer,Central,Printing,Bank Transfer,1,646.59,23,497.87,2025,2,10,646.59,497.8743,True,148.7157,NaN,Low

## Task 47

Group by Region and calculate average Order_Value.

In [79]:
df.groupby('Region')['Order_Value'].mean()

Region
Central    55650.628398
East       60277.689652
North      55000.510190
South      61522.144461
West       49119.766348
Name: Order_Value, dtype: float64

## Task 48

Group by Product_Category and calculate total sales.

In [83]:
df.groupby('Product_Category')['Order_Value'].sum()

Product_Category
Electronics    11461964.54
Furniture      12592458.34
Pantry          9388883.18
Printing       10438451.26
Stationery     12597031.28
Name: Order_Value, dtype: float64

## Task 49

Group by Payment_Method and calculate total Quantity sold.

In [84]:
df.groupby('Payment_Method')['Quantity'].sum()

Payment_Method
Bank Transfer     974
Credit Card      1119
Debit Card        965
Net Banking      1276
UPI               992
Name: Quantity, dtype: int64

## Task 50

Group by Customer_Segment and calculate average discount percentage.

In [85]:
df.groupby('Customer_Segment')['Discount_Percent'].mean()

Customer_Segment
Enterprise    14.696154
Freelancer    13.693227
School        13.956693
Startup       14.042553
Name: Discount_Percent, dtype: float64

## Task 51

Perform multi-level grouping by Region and Product_Category and compute total Order_Value.

In [86]:
df.groupby(['Region','Product_Category'])['Order_Value'].sum()

Region   Product_Category
Central  Electronics         2021177.79
         Furniture           2512922.79
         Pantry              2190459.51
         Printing            1922645.41
         Stationery          2816823.95
East     Electronics         3568207.32
         Furniture           1799125.15
         Pantry              2442482.69
         Printing            1937645.48
         Stationery          2368354.98
North    Electronics         2652235.00
         Furniture           3484002.57
         Pantry              1904881.77
         Printing            1828065.09
         Stationery          1735923.22
South    Electronics         2303230.17
         Furniture           2949158.99
         Pantry              1244276.20
         Printing            2900188.34
         Stationery          3153663.77
West     Electronics          917114.26
         Furniture           1847248.84
         Pantry              1606783.01
         Printing            1849906.94
         Stationery          2522265.36
Name: Order_Value, dtype: float64

## Task 52

Aggregate Quantity, Unit_Price, and Order_Value with multiple statistics using agg().

In [87]:
df.agg({'Quantity': ['sum','mean'],'Unit_Price': ['min','max','mean'],'Order_Value': ['sum','mean']})

      Quantity   Unit_Price   Order_Value
sum   5326.000          NaN  5.647879e+07
mean     5.326  12583.02298  5.647879e+04
min        NaN     29.21000           NaN
max        NaN  24991.95000           NaN

## Task 53

Create a pivot table showing total Order_Value by Region and Payment_Method.

## Task 54

Create a pivot table showing average Unit_Price by Product_Category and Customer_Segment.

## Task 55

Count the number of orders placed in each month.

In [99]:
df["Order_Month"].value_counts().sort_index()

Order_Month
1      86
2      72
3      76
4      82
5      88
6      91
7      80
8     101
9      85
10     88
11     71
12     80
Name: count, dtype: int64

## Task 56

Find the month with the highest total sales.

In [100]:
df.groupby("Order_Month")["Order_Value"].sum().idxmax()

np.int32(6)

## Task 57

Find the region with the highest average order value.

In [101]:
df.groupby("Region")["Order_Value"].mean().idxmax()

'South'

## Task 58

Find the product category with the highest total quantity sold.

## Task 59

Use query() to filter rows where Quantity >= 2 and Discount_Percent >= 15.

## Task 60

Select only Order_ID, Region, Product_Category, and Order_Value columns.

## Task 61

Reorder the columns in any meaningful custom order.

## Task 62

Find rows where Order_Value is above the overall average order value.

## Task 63

Find rows where Unit_Price is below the 25th percentile.

## Task 64

Find the correlation between Quantity, Unit_Price, Discount_Percent, and Order_Value.

## Task 65

Export the top 50 highest value orders to a CSV file.

## Task 66

Create a bar chart of total Order_Value by Region using Matplotlib.

## Task 67

Create a bar chart of total Quantity sold by Product_Category using Seaborn.

## Task 68

Create a histogram of Unit_Price using Matplotlib.

## Task 69

Create a histogram of Order_Value with KDE using Seaborn.

## Task 70

Create a boxplot of Order_Value by Region.

## Task 71

Create a boxplot of Unit_Price by Payment_Method.

## Task 72

Create a countplot of Customer_Segment.

## Task 73

Create a pie chart of Payment_Method distribution.

## Task 74

Create a line chart of monthly total sales.

## Task 75

Create a heatmap of correlation among numerical columns.

## Task 76

Create a scatter plot of Unit_Price vs Order_Value.

## Task 77

Create a scatter plot of Quantity vs Order_Value colored by Region using Seaborn.

## Task 78

Create a violin plot of Order_Value by Product_Category.

## Task 79

Create a stacked bar style plot of monthly sales by Region.

## Task 80

Create a pairplot for Quantity, Unit_Price, Discount_Percent, and Order_Value.